### PR TITLE
Rework install method

### PR DESCRIPTION
**Pull request by maghuro**
But keep the reference to github

### CODE REVIEW

**Comment by maghuro** [comment]
Keeping the GitHub url as you wish

**Comment by Xentrk** [comment]
I tested the method and it is causing an issue. After the install the menu appears. I then type "e" to exit. It exits but runs the script again. I think it may be a sub shell issue.

`
+ chmod 755 /jffs/addons/x3mRouting/x3mRouting_Menu.sh
+ rm /opt/bin/x3mRouting
+ ln -s /jffs/addons/x3mRouting/x3mRouting_Menu.sh /opt/bin/x3mRouting
+ x3mRouting
+ export PATH=/sbin:/bin:/usr/sbin:/usr/bin/opt/bin:/opt/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/home/wizard:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin
+ VERSION=2.0.0
+ GIT_REPO=x3mRouting
+ GITHUB_DIR=https://raw.githubusercontent.com/Xentrk/x3mRouting/x3mRouting-NG
+ LOCAL_REPO=/jffs/scripts/x3mRouting
+ COLOR_RED=\033[0;31m
+ COLOR_WHITE=\033[0m
+ COLOR_GREEN=\e[0;32m
+ Welcome_Message
+ clear
+ printf \n_______________________________________________________________________\n

_______________________________________________________________________
+ printf |                                                                     |\n
|                                                                     |
+ printf |  Welcome to the %bx3mRouting%b Installation Menu                        |\n \e[0;32m \033[0m
|  Welcome to the x3mRouting Installation Menu                        |
+ printf |  Version %s by Xentrk                                            |\n 2.0.0
|  Version 2.0.0 by Xentrk                                            |
+ printf |         ____        _         _                                     |\n
|         ____        _         _                                     |
+ printf |        |__  |      | |       | |                                    |\n
|        |__  |      | |       | |                                    |
+ printf |  __  __  _| |_ _ _ | |_  ___ | | __    ____ ____  _ _ _             |\n
|  __  __  _| |_ _ _ | |_  ___ | | __    ____ ____  _ _ _             |
+ printf |  \ \/ / |_  | %b %b \  __|/ _ \| |/ /   /  _//    \| %b %b \            |\n ` ` ` `
|  \ \/ / |_  | ` ` \  __|/ _ \| |/ /   /  _//    \| ` ` \            |
+ printf |   /  /  __| | | | |  |_ | __/|   <   (  (_ | [] || | | |            |\n
|   /  /  __| | | | |  |_ | __/|   <   (  (_ | [] || | | |            |
+ printf |  /_/\_\|___ |_|_|_|\___|\___||_|\_\[] \___\\\____/|_|_|_|            |\n
|  /_/\_\|___ |_|_|_|\___|\___||_|\_\[] \___\\____/|_|_|_|            |
+ printf |_____________________________________________________________________|\n
|_____________________________________________________________________|
+ printf |                                                                     |\n
|                                                                     |
+ printf | Requirements: jffs partition and USB drive with entware installed   |\n
| Requirements: jffs partition and USB drive with entware installed   |
+ printf |                                                                     |\n
|                                                                     |
+ printf | See the project repository at                                       |\n
| See the project repository at                                       |
+ printf | %bhttps://github.com/Xentrk/x3mRouting%b                                |\n \e[0;32m \033[0m
| https://github.com/Xentrk/x3mRouting                                |
+ printf | for helpful tips.                                                   |\n
| for helpful tips.                                                   |
+ printf |_____________________________________________________________________|\n\n
|_____________________________________________________________________|

+ Main_Menu
+ true
+ printf %b[1]%b  Install LAN Client Routing\n \e[0;32m \033[0m
[1]  Install LAN Client Routing
+ printf %b[2]%b  Install OpenVPN Client GUI, OpenVPN Event & x3mRouting.sh Script\n \e[0;32m \033[0m
[2]  Install OpenVPN Client GUI, OpenVPN Event & x3mRouting.sh Script
+ printf %b[3]%b  Install OpenVPN Event & x3mRouting.sh Script\n \e[0;32m \033[0m
[3]  Install OpenVPN Event & x3mRouting.sh Script
+ printf %b[4]%b  Install getdomainnames.sh Script\n \e[0;32m \033[0m
[4]  Install getdomainnames.sh Script
+ printf %b[5]%b  Check for updates to existing x3mRouting installation\n \e[0;32m \033[0m
[5]  Check for updates to existing x3mRouting installation
+ printf %b[6]%b  Remove x3mRouting Repository\n \e[0;32m \033[0m
[6]  Remove x3mRouting Repository
+ md5sum /jffs/addons/x3mRouting/x3mRouting_Menu.sh
+ awk {print $1}
+ localmd5=4283fc713736c8a9e81d729c8569f5dc
+ curl -fsL --retry 3 https://raw.githubusercontent.com/Xentrk/x3mRouting/x3mRouting-NG/x3mRouting_Menu.sh
+ md5sum
+ awk {print $1}
+ remotemd5=4283fc713736c8a9e81d729c8569f5dc
+ [ 4283fc713736c8a9e81d729c8569f5dc != 4283fc713736c8a9e81d729c8569f5dc ]
+ [ -d /jffs/scripts/x3mRouting ]
+ [ ! -f /jffs/scripts/x3mRouting/x3mRouting.sh ]
+ grep -c .nvram
+ ls /jffs/configs/dnsmasq.conf.add 
+ [ 0 -ge 1 ]
+ printf \n%b[e]%b  Exit Script\n \e[0;32m \033[0m

[e]  Exit Script
+ printf \n%bOption ==>%b  \e[0;32m \033[0m

Option ==> + read -r menu1
e  <<======================================= this is where I specify exit
+ Exit_Message
+ printf \n              %bhttps://github.com/Xentrk/x3mRouting%b\n \e[0;32m \033[0m\n

              https://github.com/Xentrk/x3mRouting

+ printf                       Have a Grateful Day!\n\n
                      Have a Grateful Day!

+ printf            ____        _         _                           \n
           ____        _         _
+ printf           |__  |      | |       | |                          \n
          |__  |      | |       | |
+ printf     __  __  _| |_ _ _ | |_  ___ | | __    ____ ____  _ _ _   \n
    __  __  _| |_ _ _ | |_  ___ | | __    ____ ____  _ _ _
+ printf     \ \/ / |_  | %b %b \  __|/ _ \| |/ /   /  _//    \| %b %b \ \n ` ` ` `
    \ \/ / |_  | ` ` \  __|/ _ \| |/ /   /  _//    \| ` ` \
+ printf      /  /  __| | | | |  |_ | __/|   <   (  (_ | [] || | | |  \n
     /  /  __| | | | |  |_ | __/|   <   (  (_ | [] || | | |
+ printf     /_/\_\|___ |_|_|_|\___|\___||_|\_\[] \___\\\____/|_|_|_| \n\n\n
    /_/\_\|___ |_|_|_|\___|\___||_|\_\[] \___\\____/|_|_|_|


+ exit 0   <<======================================= this is the exit 0
+ x3mRouting <<=================================the menu is executed again
+ export PATH=/sbin:/bin:/usr/sbin:/usr/bin/opt/bin:/opt/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/home/wizard:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin
+ VERSION=2.0.0
+ GIT_REPO=x3mRouting
`

**Comment by maghuro** [comment]
Can you please try this fix?

**Comment by maghuro** [comment]
Just tested, same problem.

I have an ideia, later tonight I'll try to implement it.

**Comment by maghuro** [comment]
I think it's working now.

**Comment by maghuro** [comment]
You can accept it. Fully tested and working good!

**Pull request merged**
